[project]
name = "scripts"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.6",
    "pandas>=2.3.3",
    "pillow>=11.3.0",
    "scipy>=1.16.3",
    "seaborn>=0.13.2",
]
